USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE SALES_CALLS_WH; --by default, this creates an XS Standard Warehouse
CREATE OR REPLACE DATABASE SALES_CALLS_DB;
CREATE OR REPLACE SCHEMA SALES_CALLS_SCHEMA;
CREATE OR REPLACE STAGE RAW_DATA; --to store demo assets
CREATE OR REPLACE STAGE NOTEBOOK; --to store demo assets
CREATE OR REPLACE STAGE CHATBOT_APP; --to store demo assets
USE WAREHOUSE SALES_CALLS_WH;
USE DATABASE SALES_CALLS_DB;
USE SCHEMA SALES_CALLS_SCHEMA;
-- create csv format
CREATE FILE FORMAT IF NOT EXISTS CSVFORMAT
    SKIP_HEADER = 1
    TYPE = 'CSV';
